export const APP_CONSTANTS = {
  APP_TITLE: 'Pizza Shop',
  API_ENDPOINT: 'https://api.example.com',
  ITEMS_PER_PAGE: 10,
  DEFAULT_DIAMETER: 24,
  MIN_DIAMETER: 20,
  MAX_DIAMETER: 40,
  MAX_DESCRIPTION: 32,
  MIN_BAKING_TIME:0
};
